'use client';

import React from 'react';

interface CertificateProps {
  candidateName: string;
  position: string;
  industry: string;
  score: number;
  maxScore: number;
  percentage: number;
  grade: string;
  date: Date;
  sessionId: string;
  type?: 'mock' | 'job-specific';
}

export default function Certificate({
  candidateName,
  position,
  industry,
  score,
  maxScore,
  percentage,
  grade,
  date,
  sessionId,
  type = 'mock'
}: CertificateProps) {
  const dateStr = date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const getGradeColor = (grade: string) => {
    switch (grade) {
      case 'A+':
      case 'A':
        return '#10B981'; // green-500
      case 'A-':
      case 'B+':
        return '#3B82F6'; // blue-500
      case 'B':
      case 'B-':
        return '#F59E0B'; // amber-500
      case 'C+':
      case 'C':
        return '#EF4444'; // red-500
      default:
        return '#6B7280'; // gray-500
    }
  };

  return (
    <div className="certificate-container" id="certificate">
      <div className="certificate">
        {/* Decorative Border */}
        <div className="certificate-border">
          <div className="border-pattern"></div>
        </div>

        {/* Header */}
        <div className="certificate-header">
          <div className="logo-section">
            <div className="logo">
              <span className="logo-text">AI</span>
            </div>
            <div className="company-info">
              <h1 className="company-name">AI Toolbox</h1>
              <p className="company-tagline">Professional Interview Assessment</p>
            </div>
          </div>
          
          <div className="certificate-title">
            <h2 className="title-main">Certificate of Completion</h2>
            <p className="title-subtitle">
              {type === 'job-specific' ? 'Job-Specific Interview Assessment' : 'Mock Interview Assessment'}
            </p>
          </div>
        </div>

        {/* Main Content */}
        <div className="certificate-content">
          <div className="certification-text">
            <p className="certify-text">This is to certify that</p>
            <h3 className="candidate-name">{candidateName}</h3>
            <p className="completion-text">
              has successfully completed a professional interview assessment for the position of
            </p>
            <h4 className="position-title">{position}</h4>
            <p className="industry-text">in the {industry} industry</p>
          </div>

          {/* Performance Section */}
          <div className="performance-section">
            <div className="grade-display">
              <div className="grade-circle" style={{ borderColor: getGradeColor(grade) }}>
                <span className="grade-text" style={{ color: getGradeColor(grade) }}>
                  {grade}
                </span>
              </div>
            </div>
            
            <div className="score-details">
              <div className="score-item">
                <span className="score-label">Score:</span>
                <span className="score-value">{score}/{maxScore}</span>
              </div>
              <div className="score-item">
                <span className="score-label">Percentage:</span>
                <span className="score-value">{percentage}%</span>
              </div>
            </div>
          </div>

          {/* Assessment Details */}
          <div className="assessment-details">
            <div className="detail-row">
              <span className="detail-label">Assessment Date:</span>
              <span className="detail-value">{dateStr}</span>
            </div>
            <div className="detail-row">
              <span className="detail-label">Certificate ID:</span>
              <span className="detail-value">{sessionId}</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="certificate-footer">
          <div className="signatures">
            <div className="signature-section">
              <div className="signature-line"></div>
              <p className="signature-label">AI Assessment System</p>
            </div>
            <div className="signature-section">
              <div className="signature-line"></div>
              <p className="signature-label">Date</p>
            </div>
          </div>
          
          <div className="certificate-info">
            <p className="info-text">
              This certificate is generated by AI Toolbox's advanced interview assessment system.
              The assessment evaluates technical knowledge, problem-solving abilities, and communication skills.
            </p>
            <div className="security-features">
              <p className="security-text">Certificate ID: {sessionId}</p>
              <p className="security-text">Verifiable through AI Toolbox platform</p>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .certificate-container {
          width: 100%;
          max-width: 900px;
          margin: 0 auto;
          padding: 20px;
          background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
          min-height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .certificate {
          background: white;
          width: 100%;
          max-width: 800px;
          padding: 60px;
          border-radius: 20px;
          box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
          position: relative;
          overflow: hidden;
        }

        .certificate-border {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          border: 3px solid #1e40af;
          border-radius: 20px;
          pointer-events: none;
        }

        .border-pattern {
          position: absolute;
          top: 20px;
          left: 20px;
          right: 20px;
          bottom: 20px;
          border: 1px solid #3b82f6;
          border-radius: 15px;
        }

        .certificate-header {
          text-align: center;
          margin-bottom: 50px;
        }

        .logo-section {
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: 30px;
        }

        .logo {
          width: 60px;
          height: 60px;
          background: linear-gradient(135deg, #3b82f6 0%, #1e40af 100%);
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-right: 20px;
        }

        .logo-text {
          color: white;
          font-weight: bold;
          font-size: 24px;
        }

        .company-name {
          font-size: 32px;
          font-weight: bold;
          color: #1e293b;
          margin: 0;
        }

        .company-tagline {
          font-size: 16px;
          color: #64748b;
          margin: 5px 0 0 0;
        }

        .certificate-title {
          border-bottom: 3px solid #3b82f6;
          padding-bottom: 20px;
        }

        .title-main {
          font-size: 42px;
          font-weight: bold;
          color: #1e293b;
          margin: 0;
          text-transform: uppercase;
          letter-spacing: 2px;
        }

        .title-subtitle {
          font-size: 18px;
          color: #64748b;
          margin: 10px 0 0 0;
          font-style: italic;
        }

        .certificate-content {
          text-align: center;
          margin: 40px 0;
        }

        .certify-text {
          font-size: 18px;
          color: #64748b;
          margin: 0;
        }

        .candidate-name {
          font-size: 36px;
          font-weight: bold;
          color: #1e40af;
          margin: 20px 0;
          text-transform: uppercase;
          letter-spacing: 1px;
        }

        .completion-text {
          font-size: 18px;
          color: #64748b;
          margin: 20px 0;
          line-height: 1.6;
        }

        .position-title {
          font-size: 28px;
          font-weight: bold;
          color: #1e293b;
          margin: 20px 0;
          text-transform: uppercase;
        }

        .industry-text {
          font-size: 18px;
          color: #64748b;
          margin: 10px 0 30px 0;
        }

        .performance-section {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 40px;
          margin: 40px 0;
          padding: 30px;
          background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
          border-radius: 15px;
        }

        .grade-display {
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .grade-circle {
          width: 120px;
          height: 120px;
          border: 4px solid;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          background: white;
        }

        .grade-text {
          font-size: 48px;
          font-weight: bold;
        }

        .score-details {
          display: flex;
          flex-direction: column;
          gap: 15px;
        }

        .score-item {
          display: flex;
          align-items: center;
          gap: 15px;
        }

        .score-label {
          font-size: 16px;
          color: #64748b;
          font-weight: 500;
        }

        .score-value {
          font-size: 20px;
          font-weight: bold;
          color: #1e293b;
        }

        .assessment-details {
          margin: 30px 0;
          padding: 20px;
          background: #f8fafc;
          border-radius: 10px;
        }

        .detail-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 10px 0;
          border-bottom: 1px solid #e2e8f0;
        }

        .detail-row:last-child {
          border-bottom: none;
        }

        .detail-label {
          font-size: 16px;
          color: #64748b;
          font-weight: 500;
        }

        .detail-value {
          font-size: 16px;
          color: #1e293b;
          font-weight: 600;
        }

        .certificate-footer {
          margin-top: 50px;
          padding-top: 30px;
          border-top: 2px solid #e2e8f0;
        }

        .signatures {
          display: flex;
          justify-content: space-between;
          margin-bottom: 30px;
        }

        .signature-section {
          text-align: center;
        }

        .signature-line {
          width: 200px;
          height: 2px;
          background: #1e293b;
          margin: 0 auto 10px auto;
        }

        .signature-label {
          font-size: 14px;
          color: #64748b;
          margin: 0;
        }

        .certificate-info {
          text-align: center;
        }

        .info-text {
          font-size: 14px;
          color: #64748b;
          line-height: 1.6;
          margin: 0 0 20px 0;
        }

        .security-features {
          display: flex;
          justify-content: space-between;
          font-size: 12px;
          color: #94a3b8;
        }

        .security-text {
          margin: 0;
        }

        @media print {
          .certificate-container {
            background: white;
            padding: 0;
          }
          
          .certificate {
            box-shadow: none;
            border: 2px solid #1e40af;
          }
        }
      `}</style>
    </div>
  );
} 